# set zsh as default shell
set-option -g default-shell /bin/zsh
# set the scrollup buffer (NOTE: very large buffer value with multiple tmux pane will risk eating up the machine's memory)
set-option -g history-limit 49000

# tmux is not xterm
set -g default-terminal "tmux-256color"
# This enables 24-bit true color passthrough, which xterm-256color alone doesn't provide.
set -ga terminal-overrides ",xterm-256color*:Tc"
# Above works on Linux box; However on (possibly old) macOS it can break terminal UX in tmux :/
if-shell 'uname | egrep -q Darwin' {
  set -g default-terminal "xterm-256color"
}

# make command delay short
set -sg escape-time 3

# reload the tmux cofig while using tmux
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# use vertical and horizontal symbols to split the screen
bind | split-window -h
bind - split-window -v

# count windows and panes from 1
set -g base-index 1
set -g pane-base-index 1

# set the movement in tmux panels(not windows) as vim-style
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use vi-style key bindings
set-window-option -g mode-keys vi

# make txt copied in tmux session available to system clipboard
# https://github.com/tmux/tmux/wiki/Clipboard
set -s set-clipboard external
# On linux distro eg ubuntu, use external tool eg xclip to help set clipboard
if-shell 'uname | egrep -q Linux' {
  set -s copy-command "xclip -i -selection clipboard"
}
